import { resolveDatabaseTarget } from './targets.mjs';
import { writeFile, chmod } from 'node:fs/promises';
const url = new URL(process.env.RELEASE_DB);
resolveDatabaseTarget(process.env.RELEASE_DB);
if (![undefined, 'true', 'false'].includes(process.env.RELEASE_NORMAL_JOBS)) throw new Error('RELEASE_NORMAL_JOBS must be true or false.');
const connectionLimit = Number(process.env.RELEASE_DATABASE_CONNECTION_LIMIT ?? 20);
if (!Number.isInteger(connectionLimit) || connectionLimit < 1 || connectionLimit > 80) throw new Error('The isolated connection budget must be between 1 and 80.');
const key = process.env.RELEASE_KEY;
if (!key || key.length < 32 || !process.env.TUNNEL_TOKEN) throw new Error('Isolated rehearsal credentials missing.');
const lines = { DATABASE_URL: url.href, APP_ENV: 'production', NODE_ENV: 'production', JWT_SECRET: key, ADMIN_JWT_SECRET: `${key}-admin`, MERCHANT_JWT_SECRET: `${key}-merchant`, CRON_SECRET: `${key}-cron`, REDEEM_TICKET_SECRET: `${key}-redeem`, COOKIE_NAME: 'lilink_rehearsal_token', ADMIN_COOKIE_NAME: 'lilink_rehearsal_admin_token', MERCHANT_COOKIE_NAME: 'lilink_rehearsal_merchant_token', COOKIE_DOMAIN: '.lilink.top', CLIENT_ORIGIN: 'https://release-20260920.lilink.top', SMTP_HOST: 'release-mail', SMTP_PORT: '1025', SMTP_FROM: 'LiLink Test <test@example.test>', BACKGROUND_JOBS_ENABLED: process.env.RELEASE_NORMAL_JOBS === 'true' ? 'true' : 'false', MAIL_DELIVERY_ENABLED: 'true', SENTRY_DSN: '' };
lines.DATABASE_CONNECTION_LIMIT = String(connectionLimit);
await writeFile('artifacts/release-secret/api_env', Object.entries(lines).map(([k, v]) => `${k}=${v}`).join('\n'), { mode: 0o644 });
await chmod('artifacts/release-secret/api_env', 0o644);
await writeFile('artifacts/release-secret/access-key', key, { mode: 0o600 });
await writeFile('artifacts/release-secret/tunnel-token', process.env.TUNNEL_TOKEN, { mode: 0o600 });
