const card=`<div class="match-card"><h3>Your match: Alex</h3><p>🎯 99.3% compatibility</p><p><strong>Here's why:</strong></p><ul><li>"Curiosity" and "Adventure" both made your top 4 core values</li><li>They also want someone who calls them out on their bullshit (lovingly)</li><li>You each value independence but still prioritize keeping in touch</li></ul></div>`;
let joined=true;
const app=document.querySelector('#app');
function render(){const page=location.hash.slice(1)||'home';document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+page));
if(page==='match')app.innerHTML=`<section class="match-layout"><p class="eyebrow">A thoughtful introduction</p><h1>Someone worth meeting.</h1><p class="muted">One person. A little curiosity. A real conversation.</p><p class="origin">以下卡片的文案和样式参数来自原站公开展示组件；外围布局与按钮为本地模拟。</p>${card}<div class="row space"><button class="primary" id="contact">Say hello</button><a href="#home">Back to overview ↗</a></div></section>`;
else if(page==='profile')app.innerHTML=`<section class="form"><p class="eyebrow">Local mock screen</p><h1>A little about you.</h1><p class="muted">此资料页为模拟布局，不代表原站登录后的真实设计。</p><form class="panel space" id="profile"><label>First name<input name="name" value="Jamie" required></label><label>School<input value="Stanford" readonly></label><label>Email<input value="jamie@example.invalid" readonly></label><label>A perfect Sunday<input name="sunday" value="Coffee, a long walk, and a good book."></label><button class="primary">Save locally</button><p id="saved" aria-live="polite"></p></form></section>`;
else app.innerHTML=`<p class="eyebrow">Stanford · Local mock screen</p><h1>Good things take a little chance.</h1><p class="muted intro">Welcome, Jamie. One thoughtful introduction at a time.</p><div class="grid"><div><section class="panel hero"><p class="eyebrow" style="color:#fce6df">Less swiping. More living.</p><h2>Make room for<br>someone new.</h2><p>Get to know someone beyond a profile.</p></section><section class="panel space"><div class="row"><h3 style="margin:0">Your next drop</h3><span class="tag">${joined?'You’re opted in':'Matching paused'}</span></div><p class="muted">演示状态，可切换参与或暂停。</p><button class="secondary" id="join">${joined?'Pause matching':'Opt in'}</button></section></div><div>${card}<p class="origin">↑ 原站公开匹配示例组件，Alex 与分数均为示例。</p><a class="primary" href="#match">Meet your match ↗</a><div class="line"></div><h3>Show up as yourself.</h3><p class="muted">A few details can start a good conversation.</p><a href="#profile">View your profile ↗</a></div></div>`;
const stored=JSON.parse(sessionStorage.getItem('datedrop-preview-profile')||'{}');for(const [key,value] of Object.entries(stored)){const field=document.querySelector('#profile')?.elements.namedItem(key);if(field)field.value=value;}document.querySelector('#join')?.addEventListener('click',()=>{joined=!joined;render()});document.querySelector('#contact')?.addEventListener('click',()=>document.querySelector('#modal').showModal());document.querySelector('#profile')?.addEventListener('submit',e=>{e.preventDefault();sessionStorage.setItem('datedrop-preview-profile',JSON.stringify(Object.fromEntries(new FormData(e.target))));document.querySelector('#saved').textContent='Saved for this preview session.'});}
window.addEventListener('hashchange',render);document.querySelector('.avatar').onclick=()=>location.hash='profile';document.querySelector('#close').onclick=document.querySelector('#done').onclick=()=>document.querySelector('#modal').close();render();
