export const EMAIL_MAX_LENGTH = 254;

export const PROFILE_FULL_NAME_MAX_LENGTH = 80;
export const PROFILE_HEADLINE_MAX_LENGTH = 160;
export const PROFILE_BIO_MAX_LENGTH = 1_000;
export const PROFILE_SHORT_TEXT_MAX_LENGTH = 80;
export const PROFILE_ARRAY_MAX_ITEMS = 20;
export const PROFILE_ARRAY_ITEM_MAX_LENGTH = 80;

export const CONTACT_METHOD_VALUE_MAX_LENGTH = 120;

export const REPORT_DETAILS_MAX_LENGTH = 2_000;

export const MATCH_FEEDBACK_COMMENT_MAX_LENGTH = 1_000;

export const QUESTIONNAIRE_ACKNOWLEDGEMENT_KEYS_MAX_ITEMS = 100;
export const QUESTIONNAIRE_ACKNOWLEDGEMENT_KEY_MAX_LENGTH = 128;

export const ADMIN_LIST_PAGE_MAX = 100_000;
export const ADMIN_LIST_PAGE_SIZE_MAX = 50;
export const ADMIN_SEARCH_MAX_LENGTH = 120;
export const ADMIN_ID_MAX_LENGTH = 128;
export const ADMIN_DESCRIPTION_MAX_LENGTH = 1_000;
export const ADMIN_SCHOOL_NAME_MAX_LENGTH = 120;
export const ADMIN_SCHOOL_SLUG_MAX_LENGTH = 80;
export const ADMIN_SCHOOL_DOMAIN_MAX_ITEMS = 100;
export const ADMIN_SCHOOL_DOMAIN_MAX_LENGTH = 255;
export const ADMIN_CYCLE_CODENAME_MAX_LENGTH = 120;
export const ADMIN_CYCLE_NOTES_MAX_LENGTH = 2_000;
export const ADMIN_QUESTION_KEY_MAX_LENGTH = 80;
export const ADMIN_QUESTION_PROMPT_MAX_LENGTH = 500;
export const ADMIN_QUESTION_OPTION_VALUE_MAX_LENGTH = 120;
export const ADMIN_QUESTION_OPTION_LABEL_MAX_LENGTH = 200;
export const ADMIN_QUESTION_OPTIONS_MAX_ITEMS = 50;
export const ADMIN_QUESTION_REORDER_MAX_ITEMS = 100;
export const ADMIN_REPORT_BATCH_MAX_ITEMS = 100;
export const ADMIN_REPORT_REVIEW_NOTES_MAX_LENGTH = 2_000;
export const ADMIN_SETTINGS_VALUE_MAX_LENGTH = 12;
