const MERCHANT_LOGIN_THROTTLE_TTL_MS = 60_000;
const MERCHANT_LOGIN_THROTTLE_LIMIT = 10;

export const MERCHANT_LOGIN_THROTTLE = {
  default: {
    ttl: MERCHANT_LOGIN_THROTTLE_TTL_MS,
    limit: MERCHANT_LOGIN_THROTTLE_LIMIT,
  },
};
