// Generated by scripts/images/version-shell-assets.mjs.
export const shellAssets = {
  "icons/icon.svg": "/icons/icon.f5a80339b9af.svg",
  "icons/icon-maskable.svg": "/icons/icon-maskable.97324e30979e.svg",
  "icons/contact/mail.svg": "/icons/contact/mail.5f27eaf548fa.svg",
  "icons/contact/wechat.svg": "/icons/contact/wechat.b6dfbf95938e.svg",
  "icons/contact/xiaohongshu.svg": "/icons/contact/xiaohongshu.847cacc807f5.svg",
  "icons/contact/wechat-filled.svg": "/icons/contact/wechat-filled.74b48b3d3153.svg",
  "icons/apple-touch-icon.png": "/icons/apple-touch-icon.6d9a55dda232.png",
  "icons/favicon-32.png": "/icons/favicon-32.814c031360df.png",
  "icons/icon-192.png": "/icons/icon-192.ac2ec959a657.png",
  "icons/icon-512.png": "/icons/icon-512.d972b64e510a.png",
  "icons/icon-maskable-512.png": "/icons/icon-maskable-512.e1cf52e8dd69.png",
  "fonts/playfair-display-latin.woff2": "/fonts/playfair-display-latin.5d91eb5d522a.woff2"
} as const;
