// Generated by scripts/images/generate-responsive.mjs. Do not edit.
export const staticImageManifest = {
  "/images/campus-blossom-scene-anime.5ee78102b043.webp": {
    "width": 1254,
    "height": 1254,
    "variants": [
      {
        "src": "/images/responsive/campus-blossom-scene-anime-384.fb004ec11c2a.webp",
        "width": 384,
        "height": 384
      },
      {
        "src": "/images/responsive/campus-blossom-scene-anime-640.431cf16153ee.webp",
        "width": 640,
        "height": 640
      },
      {
        "src": "/images/responsive/campus-blossom-scene-anime-750.ed99cad61336.webp",
        "width": 750,
        "height": 750
      },
      {
        "src": "/images/responsive/campus-blossom-scene-anime-828.3f05a43724b2.webp",
        "width": 828,
        "height": 828
      },
      {
        "src": "/images/responsive/campus-blossom-scene-anime-1080.c92489481a7e.webp",
        "width": 1080,
        "height": 1080
      },
      {
        "src": "/images/responsive/campus-blossom-scene-anime-1254.5ee78102b043.webp",
        "width": 1254,
        "height": 1254
      }
    ]
  },
  "/images/campus-evening-anime.2b6f7201560b.webp": {
    "width": 1672,
    "height": 941,
    "variants": [
      {
        "src": "/images/responsive/campus-evening-anime-384.33380363016b.webp",
        "width": 384,
        "height": 216
      },
      {
        "src": "/images/responsive/campus-evening-anime-640.b4a1e977e654.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/images/responsive/campus-evening-anime-750.1c616034e92e.webp",
        "width": 750,
        "height": 422
      },
      {
        "src": "/images/responsive/campus-evening-anime-828.22b8df2aacf7.webp",
        "width": 828,
        "height": 466
      },
      {
        "src": "/images/responsive/campus-evening-anime-1080.af38de41ec8e.webp",
        "width": 1080,
        "height": 608
      },
      {
        "src": "/images/responsive/campus-evening-anime-1200.7a3a0e9428cd.webp",
        "width": 1200,
        "height": 675
      },
      {
        "src": "/images/responsive/campus-evening-anime-1672.2b6f7201560b.webp",
        "width": 1672,
        "height": 941
      }
    ]
  },
  "/images/campus-clean-romance.fdd0f4cc2596.webp": {
    "width": 1672,
    "height": 941,
    "variants": [
      {
        "src": "/images/responsive/campus-clean-romance-384.64978902216b.webp",
        "width": 384,
        "height": 216
      },
      {
        "src": "/images/responsive/campus-clean-romance-640.644e1997ce06.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/images/responsive/campus-clean-romance-750.94bd761ed9ac.webp",
        "width": 750,
        "height": 422
      },
      {
        "src": "/images/responsive/campus-clean-romance-1080.2280537cc14c.webp",
        "width": 1080,
        "height": 608
      },
      {
        "src": "/images/responsive/campus-clean-romance-1672.fdd0f4cc2596.webp",
        "width": 1672,
        "height": 941
      }
    ]
  },
  "/images/campus-couple-anime.74b2881afd58.webp": {
    "width": 1672,
    "height": 941,
    "variants": [
      {
        "src": "/images/responsive/campus-couple-anime-384.46a5b290ea13.webp",
        "width": 384,
        "height": 216
      },
      {
        "src": "/images/responsive/campus-couple-anime-640.53b20c28e535.webp",
        "width": 640,
        "height": 360
      },
      {
        "src": "/images/responsive/campus-couple-anime-750.4a7b32d454bd.webp",
        "width": 750,
        "height": 422
      },
      {
        "src": "/images/responsive/campus-couple-anime-1080.52f68246ead5.webp",
        "width": 1080,
        "height": 608
      },
      {
        "src": "/images/responsive/campus-couple-anime-1672.74b2881afd58.webp",
        "width": 1672,
        "height": 941
      }
    ]
  },
  "/images/one-to-one-minimal.6c30b4067e80.webp": {
    "width": 1600,
    "height": 1067,
    "variants": [
      {
        "src": "/images/responsive/one-to-one-minimal-384.875bec6a6fff.webp",
        "width": 384,
        "height": 256
      },
      {
        "src": "/images/responsive/one-to-one-minimal-640.7ca34a20bb85.webp",
        "width": 640,
        "height": 427
      },
      {
        "src": "/images/responsive/one-to-one-minimal-750.8d0c2e20b590.webp",
        "width": 750,
        "height": 500
      },
      {
        "src": "/images/responsive/one-to-one-minimal-828.596cf085f6a2.webp",
        "width": 828,
        "height": 552
      },
      {
        "src": "/images/responsive/one-to-one-minimal-1080.575fd7d797f5.webp",
        "width": 1080,
        "height": 720
      },
      {
        "src": "/images/responsive/one-to-one-minimal-1200.c529053faa6b.webp",
        "width": 1200,
        "height": 800
      },
      {
        "src": "/images/responsive/one-to-one-minimal-1600.6c30b4067e80.webp",
        "width": 1600,
        "height": 1067
      }
    ]
  },
  "/images/about/member-01.486b9b138019.webp": {
    "width": 336,
    "height": 336,
    "variants": [
      {
        "src": "/images/responsive/member-01-112.d74d2ce6b13f.webp",
        "width": 112,
        "height": 112
      },
      {
        "src": "/images/responsive/member-01-224.f79d64247cb3.webp",
        "width": 224,
        "height": 224
      },
      {
        "src": "/images/responsive/member-01-336.486b9b138019.webp",
        "width": 336,
        "height": 336
      }
    ]
  },
  "/images/about/member-02.b6fbc6031cdb.webp": {
    "width": 336,
    "height": 336,
    "variants": [
      {
        "src": "/images/responsive/member-02-112.08a45e112834.webp",
        "width": 112,
        "height": 112
      },
      {
        "src": "/images/responsive/member-02-224.18872736efd2.webp",
        "width": 224,
        "height": 224
      },
      {
        "src": "/images/responsive/member-02-336.b6fbc6031cdb.webp",
        "width": 336,
        "height": 336
      }
    ]
  },
  "/images/about/devillord6321.016e14db36ed.webp": {
    "width": 235,
    "height": 336,
    "variants": [
      {
        "src": "/images/responsive/devillord6321-112.4b3d3e7575ac.webp",
        "width": 112,
        "height": 160
      },
      {
        "src": "/images/responsive/devillord6321-224.ee18d98c398d.webp",
        "width": 224,
        "height": 320
      },
      {
        "src": "/images/responsive/devillord6321-235.016e14db36ed.webp",
        "width": 235,
        "height": 336
      }
    ]
  },
  "/images/match-letter-handwritten.8440550c4fe2.webp": {
    "width": 1254,
    "height": 1254,
    "variants": [
      {
        "src": "/images/responsive/match-letter-handwritten-384.60e16dd3f61e.webp",
        "width": 384,
        "height": 384
      },
      {
        "src": "/images/responsive/match-letter-handwritten-640.5588d371e1c9.webp",
        "width": 640,
        "height": 640
      },
      {
        "src": "/images/responsive/match-letter-handwritten-750.983974c129ab.webp",
        "width": 750,
        "height": 750
      },
      {
        "src": "/images/responsive/match-letter-handwritten-828.c9bf9ee5a106.webp",
        "width": 828,
        "height": 828
      },
      {
        "src": "/images/responsive/match-letter-handwritten-1080.128814fb3e91.webp",
        "width": 1080,
        "height": 1080
      },
      {
        "src": "/images/responsive/match-letter-handwritten-1254.8440550c4fe2.webp",
        "width": 1254,
        "height": 1254
      }
    ]
  }
} as const;

export type StaticImageSource = keyof typeof staticImageManifest;
